### ISSUE TITLE
Prisma Node Generator Facades

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/specs#152]
[Copied from our notion](https://www.notion.so/prismaio/Prisma-Node-Generator-Facades-cace5ed3194848bb93bf7391aea59970)

# Summary

This proposal aims to reconcile the elegance of generating into node_modules with the tooling complications that arise from this approach, such as package pruning when certain yarn/npm commands are run.

# Motivation

1. Users who have _reported_ the pruning problem include:
   - Mohammad Rajabifard [on slack](https://prisma.slack.com/archives/CKQTGR6T0/p1568641990013500)
   - Chris on [PhotonJS GH Issues](https://github.com/prisma/photonjs/issues/88#issuecomment-522047264)
2. Also, users probably expect to have a clear idea about what dependencies they are bringing with them into production. Yet, generators obscure this when they are installed into devDependencies and produce ephemeral packages imported like `@generated/foo`. This novelty provides no benefit for the Prisma Generator system but does increase the bar for users reaching comfort with them. We definitely do not want that, if avoidable.

# Proposal

### Overview

A node generator would have a layout like so:

    |- src/
    |  |- runtime/          <-- optional
    |     |- index.ts
    |  |- generator/
    |     |- index.ts
    |	    |- ...
    |- package.json

`generator/*` would contain the code run by `$ prisma generate`. This is what we think of as a generator today.

`runtime/index.ts` would contain placeholder content intended to be replaced by result of running prisma generate. Said content could and should be something helping the user fall into the pit of success (examples below). Finally, this part of a generator codebase should be optional, with a good default provided if omitted (detail below).

`package.json` `.main` would point to `src/runtime/index.ts` or like, e.g. `dist/runtime/index.js` for a built library.

Users would install the package as a production dependency, like any other:

    yarn add @prisma/foo

Then they would import it, like any other:

    import * as Foo from "@prisma/foo"

At this point, TypeScript users would already be seeing static error messages.

_Note: It would be great if we could produce informative static type error messages approaching what we can achieve in runtime feedback, but unlikely._

Their next step might be to resolve those static error messages by declaring their generator in `prisma.schema` and running generation:
```
    generator foo {
      provider = "foo"
    }
```
```
    $ prisma generate
```
Behind the scenes Prisma CLI would execute `$ foo`. The returned data would be output to files `node_modules/@prisma/foo/runtime/{index.js, index.d.ts}`. Because the files would be injected into an-actually-depended-upon-package, they would not get removed by pruning.

### Escape Hatch for End-Users

If a user wanted to escape the facade system, all they might have to do is:

1.  Install `@prisma/foo` as a devDependency:

        yarn add --dev @prisma/foo

2.  Set an explicit `output` in their generator definition block:

        generator foo {
          provider = "foo"
          output = "/my/custom/path"
        }

Reasons to escape the facade system should be scrutinized. The vast majority of users should not need this, and we should not talk about it except in advanced/by-the-way contexts.

### Pit of Success Facades for End-Users

An **_example_** `src/runtime/index.ts`

    import * as Package from '../../package'

    console.error(`
      Hey, it looks like you forgot to run $ prisma genereate.
      Also please make sure to have the following in your prisma.schema:

        generator your-name-here {
          provider = "${Package.name}"
        }
    `)

    process.exit(101)

The skies the limit but here are some more examples of how we could help users:

- Detect if their prisma.schema file already has the generate block setup or not in order to better contextualize the error message.
- Help generator authors with special helper functions exported by the Prisma Node SDK to craft good facades.

### Default Facades for Generator Authors

Generator authors would probably often find some kind of default facade that we could provide serviceable. We could do this when a generator author omits `facade/*` in their codebase.

Providing a default facade like this would imply having some kind of SDK CLI to package their generator, which today we do not have.

# Design Details

A prototype is needed to vet the ideas herein.

**Comment by jasonkuhrt** [comment]
CC @timsuchanek @Weakky @schickling

**Comment by divyenduz** [comment]
We did try this approach of having a "placeholder" package (even listed into `package.json` dependencies) and generated into it. 

The issue with this was that running `yarn install` replaced the generated content with the placeholder content of the package and some CI systems (Heroku, Apex Up for example) have the following sequence of steps: 

1. `yarn` - Installs deps, optionally, generates via post install hook
2. `yarn prisma2 generate` - explicit generation
3. After the user defined steps, system has a custom prune code, that replaces deletes the generated content if it does not exist in `package.json` and replaces it with its placeholder content when the content does not match. 

In this proposal, I think you suggest that we ship the runtime in the placeholder package and generate the types (please tell me if I am wrong?). I think it should exhibit the same pruning/cleaning behavior. Do you have a reason to believe otherwise? 

Note that this approach might work when developing as `yarn prune` (or a custom equivalient) is not called. 

Please let me know if I am missing something?

**Comment by jasonkuhrt** [comment]
> In this proposal, I think you suggest that we ship the runtime in the placeholder package and generate the types (please tell me if I am wrong?).

Not quite. The runtime folder ***contents*** get replaced in my proposal.

> I think it should exhibit the same pruning/cleaning behavior. Do you have a reason to believe otherwise?

That's not my understanding, but I will confirm this with a prototype and report results back to this thread.

**Comment by divyenduz** [comment]
> but I will confirm this with a prototype and report results back to this thread.

Thanks, while you are at it, please give it a go with a couple of deployment platforms like Heroku, Apex Up, Netlify etc

Please feel free to use these for platform specific reference: https://github.com/prisma/prisma-examples/tree/prisma2/deployment-platforms/

**Comment by jasonkuhrt** [comment]
@divyenduz first results are up, currently here: https://github.com/jasonkuhrt/explore-foreign-file-node-modules. Pruning is resolved. But yarn appears to rebuild all packages when adding a package, causing foreign content to get wiped.

**Comment by timsuchanek** [comment]
@jasonkuhrt do I understand correctly that when I do `yarn add another-package`, that the content of the facade package is wiped?
Then the issue Mo posted in Slack is not solved.

**Comment by jasonkuhrt** [comment]
@timsuchanek correct, [due to a yarn bug](https://github.com/yarnpkg/yarn/issues/4703). NPM does not suffer from that issue. We could invest energy into fixing yarn, rather than working around it.

I've updated my exploration to make this clear.

**Comment by divyenduz** [comment]
The only thing that I would add here is that some platforms have custom pruning (not just `yarn prune` or `npm prune`) and that is something we might have to test for. 

Maybe they are running into the mentioned `yarn prune` bug but since there is no way for us to see they prune implementation, it is hard to suggest that if it would work.

**Comment by jasonkuhrt** [comment]
> some platforms have custom pruning (not just yarn prune or npm prune) and that is something we might have to test for.

Can you give some examples? Sounds like you mean build systems which apply some kind of bundling logic?

> but since there is no way for us to see they prune implementation

I'm not sure which prune implementation you mean?

**Comment by jasonkuhrt** [comment]
Looking at the state of yarn: 1800 issues 115 PRs and [dwindling code frequency](https://github.com/yarnpkg/yarn/graphs/code-frequency), I am not super optimistic that we can just go in there and have the yarn issue resolved in a matter of days. I am not concluding it is not worth it, just my first impression.

**Comment by jasonkuhrt** [comment]
@timsuchanek found an elegant solution to the yarn problem https://github.com/prisma/photonjs/issues/262#issuecomment-543224207.
